{
  "configurations": {
    "CVE_data_version": "4.0",
    "nodes": []
  },
  "cve": {
    "CVE_data_meta": {
      "ASSIGNER": "secalert@redhat.com",
      "ID": "CVE-2025-32051"
    },
    "data_format": "MITRE",
    "data_type": "CVE",
    "data_version": "4.0",
    "description": {
      "description_data": [
        {
          "lang": "en",
          "value": "A flaw was found in libsoup. The libsoup soup_uri_decode_data_uri() function may crash when processing malformed data URI. This flaw allows an attacker to cause a denial of service (DoS)."
        }
      ]
    },
    "problemtype": {
      "problemtype_data": [
        {
          "description": []
        }
      ]
    },
    "references": {
      "reference_data": [
        {
          "name": "https://access.redhat.com/security/cve/CVE-2025-32051",
          "refsource": "",
          "tags": [],
          "url": "https://access.redhat.com/security/cve/CVE-2025-32051"
        },
        {
          "name": "RHBZ#2357068",
          "refsource": "",
          "tags": [],
          "url": "https://bugzilla.redhat.com/show_bug.cgi?id=2357068"
        }
      ]
    }
  },
  "impact": {},
  "lastModifiedDate": "2025-04-07T14:18Z",
  "publishedDate": "2025-04-03T14:15Z"
}