{
  "configurations": {
    "CVE_data_version": "4.0",
    "nodes": []
  },
  "cve": {
    "CVE_data_meta": {
      "ASSIGNER": "security-advisories@github.com",
      "ID": "CVE-2025-22153"
    },
    "data_format": "MITRE",
    "data_type": "CVE",
    "data_version": "4.0",
    "description": {
      "description_data": [
        {
          "lang": "en",
          "value": "RestrictedPython is a tool that helps to define a subset of the Python language which allows to provide a program input into a trusted environment. Via a type confusion bug in versions of the CPython interpreter starting in 3.11 and prior to 3.13.2 when using `try/except*`, RestrictedPython starting in version 6.0 and prior to version 8.0 could be bypassed. The issue is patched in version 8.0 of RestrictedPython by removing support for `try/except*` clauses. No known workarounds are available."
        }
      ]
    },
    "problemtype": {
      "problemtype_data": [
        {
          "description": [
            {
              "lang": "en",
              "value": "CWE-843"
            }
          ]
        }
      ]
    },
    "references": {
      "reference_data": [
        {
          "name": "https://github.com/zopefoundation/RestrictedPython/commit/48a92c5bb617a647cffd0dadd4d5cfe626bcdb2f",
          "refsource": "",
          "tags": [],
          "url": "https://github.com/zopefoundation/RestrictedPython/commit/48a92c5bb617a647cffd0dadd4d5cfe626bcdb2f"
        },
        {
          "name": "https://github.com/zopefoundation/RestrictedPython/security/advisories/GHSA-gmj9-h825-chq2",
          "refsource": "",
          "tags": [],
          "url": "https://github.com/zopefoundation/RestrictedPython/security/advisories/GHSA-gmj9-h825-chq2"
        }
      ]
    }
  },
  "impact": {},
  "lastModifiedDate": "2025-01-23T18:15Z",
  "publishedDate": "2025-01-23T18:15Z"
}