{
  "configurations": {
    "CVE_data_version": "4.0",
    "nodes": [
      {
        "children": [],
        "cpe_match": [
          {
            "cpe23Uri": "cpe:2.3:o:redhat:389_directory_server:-:*:*:*:*:*:*:*",
            "cpe_name": [],
            "vulnerable": true
          },
          {
            "cpe23Uri": "cpe:2.3:o:redhat:enterprise_linux:9.0:*:*:*:*:*:*:*",
            "cpe_name": [],
            "vulnerable": true
          },
          {
            "cpe23Uri": "cpe:2.3:a:redhat:directory_server:12.0:*:*:*:*:*:*:*",
            "cpe_name": [],
            "vulnerable": true
          }
        ],
        "operator": "OR"
      }
    ]
  },
  "cve": {
    "CVE_data_meta": {
      "ASSIGNER": "secalert@redhat.com",
      "ID": "CVE-2024-6237"
    },
    "data_format": "MITRE",
    "data_type": "CVE",
    "data_version": "4.0",
    "description": {
      "description_data": [
        {
          "lang": "en",
          "value": "A flaw was found in the 389 Directory Server. This flaw allows an unauthenticated user to cause a systematic server crash while sending a specific extended search request, leading to a denial of service."
        }
      ]
    },
    "problemtype": {
      "problemtype_data": [
        {
          "description": [
            {
              "lang": "en",
              "value": "NVD-CWE-noinfo"
            }
          ]
        }
      ]
    },
    "references": {
      "reference_data": [
        {
          "name": "RHSA-2024:4997",
          "refsource": "",
          "tags": [],
          "url": "https://access.redhat.com/errata/RHSA-2024:4997"
        },
        {
          "name": "RHSA-2024:5192",
          "refsource": "",
          "tags": [],
          "url": "https://access.redhat.com/errata/RHSA-2024:5192"
        },
        {
          "name": "https://access.redhat.com/security/cve/CVE-2024-6237",
          "refsource": "",
          "tags": [
            "Vendor Advisory"
          ],
          "url": "https://access.redhat.com/security/cve/CVE-2024-6237"
        },
        {
          "name": "https://access.redhat.com/security/cve/CVE-2024-6237",
          "refsource": "",
          "tags": [
            "Vendor Advisory"
          ],
          "url": "https://access.redhat.com/security/cve/CVE-2024-6237"
        },
        {
          "name": "RHBZ#2293579",
          "refsource": "",
          "tags": [
            "Issue Tracking"
          ],
          "url": "https://bugzilla.redhat.com/show_bug.cgi?id=2293579"
        },
        {
          "name": "RHBZ#2293579",
          "refsource": "",
          "tags": [
            "Issue Tracking"
          ],
          "url": "https://bugzilla.redhat.com/show_bug.cgi?id=2293579"
        },
        {
          "name": "https://github.com/389ds/389-ds-base/issues/5989",
          "refsource": "",
          "tags": [
            "Issue Tracking"
          ],
          "url": "https://github.com/389ds/389-ds-base/issues/5989"
        },
        {
          "name": "https://github.com/389ds/389-ds-base/issues/5989",
          "refsource": "",
          "tags": [
            "Issue Tracking"
          ],
          "url": "https://github.com/389ds/389-ds-base/issues/5989"
        }
      ]
    }
  },
  "impact": {
    "baseMetricV3": {
      "cvssV3": {
        "attackComplexity": "LOW",
        "attackVector": "NETWORK",
        "availabilityImpact": "HIGH",
        "baseScore": 6.5,
        "baseSeverity": "MEDIUM",
        "confidentialityImpact": "NONE",
        "integrityImpact": "NONE",
        "privilegesRequired": "LOW",
        "scope": "UNCHANGED",
        "userInteraction": "NONE",
        "vectorString": "CVSS:3.1/AV:N/AC:L/PR:L/UI:N/S:U/C:N/I:N/A:H",
        "version": "3.1"
      },
      "exploitabilityScore": 2.8,
      "impactScore": 3.6
    }
  },
  "lastModifiedDate": "2024-11-21T09:49Z",
  "publishedDate": "2024-07-09T17:15Z"
}